# Generated by Django 4.0.3 on 2022-04-10 09:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(98), django.core.validators.MinValueValidator(12)])),
                ('font_type', models.CharField(choices=[('reg', 'Regular'), ('italic', 'Italic'), ('bold', 'Bold'), ('bold italic', 'Bold & Italic')], max_length=25)),
                ('theme_type', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Monokai', 'Monokai'), ('Chocolate', 'Chocolate')], max_length=25)),
                ('font_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reapp.font')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
