# Generated by Django 4.0.3 on 2022-04-01 07:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(choices=[('Vollkorn', 'Vollkorn'), ('Red Hat Mono', 'Red Hat Mono'), ('Open Sans', 'Open Sans')], max_length=63)),
                ('weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(400)])),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Italic', 'Italic')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('font_size', models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(98), django.core.validators.MinValueValidator(12)])),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Monokai', 'Monokai'), ('Chocolate', 'Chocolate')], max_length=20)),
                ('font', models.ManyToManyField(to='reapp.font')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
