# Generated by Django 4.0.3 on 2022-03-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('font_size', models.IntegerField()),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Monokai', 'Monokai'), ('Chocolate', 'Chocolate')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
