# Generated by Django 4.0.3 on 2022-03-31 13:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reapp', '0002_text_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('family', models.CharField(choices=[('Vollkorn', 'Vollkorn'), ('Red Hat Mono', 'Red Hat Mono'), ('Open Sans', 'Open Sans')], max_length=63)),
                ('weight', models.IntegerField(default=400, validators=[django.core.validators.MaxValueValidator(900), django.core.validators.MinValueValidator(400)])),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Italic', 'Italic')], max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='text',
            name='font_size',
            field=models.IntegerField(default=16, validators=[django.core.validators.MaxValueValidator(98), django.core.validators.MinValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
