# Generated by Django 4.0.3 on 2022-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0003_font_text_user_alter_text_font_size_alter_text_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='font',
            name='url',
        ),
        migrations.AddField(
            model_name='text',
            name='font',
            field=models.ManyToManyField(to='reapp.font'),
        ),
    ]
