# Generated by Django 4.0.3 on 2022-04-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0003_remove_text_theme_text_theme_type_delete_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='font',
        ),
        migrations.AddField(
            model_name='text',
            name='font_family',
            field=models.CharField(choices=[('Vollkorn', 'Vollkorn'), ('Red Hat Mono', 'Red Hat Mono'), ('Open Sans', 'Open Sans'), ('Roboto Slab', 'Roboto Slab')], max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='font_type',
            field=models.CharField(choices=[('', 'Regular'), ('italic', 'Italic'), ('bold', 'Bold')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='theme_type',
            field=models.CharField(choices=[('while black', 'Light'), ('black white', 'Dark'), ('black red', 'Monokai'), ('brown white', 'Chocolate')], max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Font',
        ),
    ]
