# Generated by Django 4.0.3 on 2022-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0005_alter_text_font_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='font_type',
            field=models.CharField(choices=[('reg', 'Regular'), ('italic', 'Italic'), ('bold', 'Bold'), ('bold italic', 'Bold & Italic')], max_length=25, null=True),
        ),
    ]
