# Generated by Django 4.0.3 on 2022-04-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0006_alter_text_font_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='date_of_creation',
        ),
        migrations.RemoveField(
            model_name='text',
            name='date_of_recent_change',
        ),
    ]
