# Generated by Django 4.0.3 on 2022-04-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0007_remove_text_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='theme_type',
            field=models.CharField(choices=[('while black', 'Light'), ('black white', 'Dark'), ('black red', 'Monokai'), ('brown yellow', 'Chocolate')], max_length=25, null=True),
        ),
    ]
