# Generated by Django 4.0.3 on 2022-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0009_alter_text_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='theme_type',
            field=models.CharField(choices=[('white black', 'Light'), ('black white', 'Dark'), ('black red', 'Monokai'), ('brown yellow', 'Chocolate')], max_length=25, null=True),
        ),
    ]
