# Generated by Django 4.0.3 on 2022-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0010_alter_text_theme_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='theme_type',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Monokai', 'Monokai'), ('Chocolate', 'Chocolate')], max_length=25, null=True),
        ),
    ]
